### ISSUE TITLE
add automated TOTP

### ISSUE THREAD

**Issue by behrisch** [arcivanov/pypi-cleanup#24]
Since pypi will probably enforce 2FA sooner or later, a way to generate TOTP automatically is probably the easiest to keep the pypi-cleanup usable without user interaction. Fortunately there is https://pyauth.github.io/pyotp/. I would go on and work on it but would like to hear your opinions on it.

**Comment by arcivanov** [comment]
I would be interested in learning what do you have in mind? In order to not have any user interaction you will be required to store the TOTP secret key locally somewhere somehow. The PYOTP further notes it's a server-side library, but I assume the code there can be adapted to be used by the client.

If you have a local secret of TOTP on your machine the purpose of the TOTP is defeated entirely. Furthermore if you want no human interaction you have to store the password locally as well and keeping both TOTP secret and the password on the same machine being able to autonomously retrieve them is, basically, the biggest security disaster possible in the making. 

Unless of course I'm missing something in your proposed feature.

**Comment by behrisch** [comment]
I don't think you are missing anything. I will need to store the secret and the token (basically the password but with a limited range) locally. The point is that I want my cleanup automated and I am only doing it for test.pypi.org where we publish our nightly builds. I do not store the secret on my local machine but on the build server in a corporate environment (which may be better or worse security wise ;-)). I know that this is circumventing TOTP somehow but it seems to be the only way since pypi is not providing any other API except for uploading.

**Comment by behrisch** [comment]
You are right, it is probably a bad idea and trying to get some automated cleanup in place directly from github is the better choice
